const VOICE_JOSH   = 'TxGEqnHWrfWFTfGW9XjX'; // male, deep & warm
const VOICE_RACHEL = '21m00Tcm4TlvDq8ikWAM'; // female, warm narrator

const AUTHORS = {
  'Ram Dass':                  { gender: 'm', voiceId: VOICE_JOSH,   music: 'soft ambient eastern meditation, gentle sitar drone, 1960s warm and present' },
  'Baba Ram Dass':             { gender: 'm', voiceId: VOICE_JOSH,   music: 'soft ambient eastern meditation, gentle sitar drone, 1960s warm and present' },
  'Ernest Hemingway':          { gender: 'm', voiceId: VOICE_JOSH,   music: 'warm acoustic piano, contemplative americana, 1940s intimate and honest' },
  'Mark Twain':                { gender: 'm', voiceId: VOICE_JOSH,   music: 'gentle americana folk guitar, warm and wise, 1880s riverside' },
  'Bashar':                    { gender: 'm', voiceId: VOICE_JOSH,   music: 'modern ambient synth, expansive and uplifting, cosmic and open' },
  'Rumi':                      { gender: 'm', voiceId: VOICE_JOSH,   music: 'Persian oud and ney flute, mystical and warm, 13th century Sufi longing' },
  'Lao Tzu':                   { gender: 'm', voiceId: VOICE_JOSH,   music: 'ancient Chinese guqin strings, minimalist and flowing, wu wei' },
  'Marcus Aurelius':           { gender: 'm', voiceId: VOICE_JOSH,   music: 'sparse Roman chamber strings, noble and measured, ancient Mediterranean' },
  'Epictetus':                 { gender: 'm', voiceId: VOICE_JOSH,   music: 'sparse ancient lyre, stoic and grounding, Greek morning light' },
  'Seneca':                    { gender: 'm', voiceId: VOICE_JOSH,   music: 'Roman chamber strings, thoughtful and wise, late afternoon calm' },
  'Khalil Gibran':             { gender: 'm', voiceId: VOICE_JOSH,   music: 'Lebanese oud and cello, poetic and warm, early 1900s Mediterranean night' },
  'Viktor Frankl':             { gender: 'm', voiceId: VOICE_JOSH,   music: 'sparse piano, resilient and hopeful, mid 20th century European introspection' },
  'Carl Jung':                 { gender: 'm', voiceId: VOICE_JOSH,   music: 'chamber piano, introspective and deep, early 20th century Swiss study' },
  'Alan Watts':                { gender: 'm', voiceId: VOICE_JOSH,   music: 'ambient zen, 1960s California, soft playful and open' },
  'Thich Nhat Hanh':           { gender: 'm', voiceId: VOICE_JOSH,   music: 'tibetan bowls fading into silence, breathing space, Buddhist morning' },
  'Neville Goddard':           { gender: 'm', voiceId: VOICE_JOSH,   music: 'uplifting soft strings, hopeful and expansive, 1950s manifestation warmth' },
  'James Allen':               { gender: 'm', voiceId: VOICE_JOSH,   music: 'warm Victorian piano, reflective and earnest, 1900s morning study' },
  'Wayne Dyer':                { gender: 'm', voiceId: VOICE_JOSH,   music: 'modern meditation ambient, soft synth pad, uplifting and spacious' },
  'Deepak Chopra':             { gender: 'm', voiceId: VOICE_JOSH,   music: 'healing ambient, soft bells and synth, spacious and luminous' },
  'Joseph Campbell':           { gender: 'm', voiceId: VOICE_JOSH,   music: 'cinematic orchestral, heroic and mythic journey, mid 20th century' },
  'Hafiz':                     { gender: 'm', voiceId: VOICE_JOSH,   music: 'Persian strings and ney, ecstatic and warm, 14th century Sufi tavern' },
  'Jack Kornfield':            { gender: 'm', voiceId: VOICE_JOSH,   music: 'tibetan bowls, soft and compassionate, Buddhist forest morning' },
  'Jiddu Krishnamurti':        { gender: 'm', voiceId: VOICE_JOSH,   music: 'sparse piano, questioning and open, mid 20th century clarity' },
  'Mooji':                     { gender: 'm', voiceId: VOICE_JOSH,   music: 'Indian ambient drone, still and present, pure awareness' },
  'Adyashanti':                { gender: 'm', voiceId: VOICE_JOSH,   music: 'modern ambient silence, open and spacious, no separation' },
  'Henry David Thoreau':       { gender: 'm', voiceId: VOICE_JOSH,   music: 'American folk and birdsong, 1850s Walden Pond morning, intimate and wild' },
  'Ralph Waldo Emerson':       { gender: 'm', voiceId: VOICE_JOSH,   music: 'warm New England piano, transcendent and hopeful, 1840s' },
  'Walt Whitman':              { gender: 'm', voiceId: VOICE_JOSH,   music: 'expansive americana, open road and celebration, 1850s' },
  'Albert Einstein':           { gender: 'm', voiceId: VOICE_JOSH,   music: 'European classical piano, curious and gentle, early 20th century' },
  'Mahatma Gandhi':            { gender: 'm', voiceId: VOICE_JOSH,   music: 'Indian classical sitar, peaceful and resolute, early 20th century' },
  'Buddha':                    { gender: 'm', voiceId: VOICE_JOSH,   music: 'tibetan singing bowls, deep resonance, ancient and still, dawn' },
  'Aristotle':                 { gender: 'm', voiceId: VOICE_JOSH,   music: 'ancient Greek lyre, measured and harmonious, golden hour Athens' },
  'Confucius':                 { gender: 'm', voiceId: VOICE_JOSH,   music: 'ancient Chinese guqin, wise and gentle, morning contemplation' },
  'Napoleon Hill':             { gender: 'm', voiceId: VOICE_JOSH,   music: 'upbeat 1930s piano, determined and optimistic, American ambition' },
  'Carl Sagan':                { gender: 'm', voiceId: VOICE_JOSH,   music: 'cosmic ambient synth, vast and wonder-filled, 1980s stargazing' },
  'Nikola Tesla':              { gender: 'm', voiceId: VOICE_JOSH,   music: 'early 20th century European strings with subtle electric hum, precise' },
  'Chuang Tzu':                { gender: 'm', voiceId: VOICE_JOSH,   music: 'ancient Chinese bamboo flute, flowing and free, dreaming and awake' },
  'Plato':                     { gender: 'm', voiceId: VOICE_JOSH,   music: 'ancient Greek lyre, philosophical and illuminating, cave and light' },
  'William Blake':             { gender: 'm', voiceId: VOICE_JOSH,   music: 'romantic English strings, visionary and wild, 1790s prophetic' },
  'Rabindranath Tagore':       { gender: 'm', voiceId: VOICE_JOSH,   music: 'Bengali classical strings and harmonium, poetic and warm, early 1900s' },
  'Hermann Hesse':             { gender: 'm', voiceId: VOICE_JOSH,   music: 'European chamber piano, seeking and introspective, 1920s forest' },
  'Fyodor Dostoevsky':         { gender: 'm', voiceId: VOICE_JOSH,   music: 'Russian strings, intense and searching, 1860s candlelight' },
  'Leo Tolstoy':               { gender: 'm', voiceId: VOICE_JOSH,   music: 'Russian piano, vast and contemplative, 1870s winter stillness' },
  'Rainer Maria Rilke':        { gender: 'm', voiceId: VOICE_JOSH,   music: 'German chamber strings, tender and questioning, early 1900s dusk' },
  'Pablo Neruda':              { gender: 'm', voiceId: VOICE_JOSH,   music: 'Latin acoustic guitar, passionate and warm, mid 20th century Chile' },
  'Dōgen':                     { gender: 'm', voiceId: VOICE_JOSH,   music: 'Japanese shakuhachi flute, Zen and spacious, 13th century dawn' },
  'Shunryu Suzuki':            { gender: 'm', voiceId: VOICE_JOSH,   music: 'Zen ambient, soft bells and breath, beginner mind open' },
  'Sri Aurobindo':             { gender: 'm', voiceId: VOICE_JOSH,   music: 'Indian classical harmonium, philosophical and luminous, Pondicherry' },
  'Nisargadatta Maharaj':      { gender: 'm', voiceId: VOICE_JOSH,   music: 'Indian ambient drone, still and direct, Advaita beedi smoke' },
  'Swami Vivekananda':         { gender: 'm', voiceId: VOICE_JOSH,   music: 'Indian classical strings, powerful and inspiring, 1890s Chicago' },
  'Paramahansa Yogananda':     { gender: 'm', voiceId: VOICE_JOSH,   music: 'devotional Indian harmonium, peaceful and divine, Kriya dawn' },
  'Abraham-Hicks':             { gender: 'f', voiceId: VOICE_RACHEL, music: 'modern uplifting ambient, warm synth, expansive and joyful vortex' },
  'Martin Luther King Jr.':    { gender: 'm', voiceId: VOICE_JOSH,   music: 'gospel piano, powerful and hopeful, 1960s American justice' },
  'Nelson Mandela':            { gender: 'm', voiceId: VOICE_JOSH,   music: 'South African strings, dignified and triumphant, Robben Island dawn' },
  'Frederick Douglass':        { gender: 'm', voiceId: VOICE_JOSH,   music: 'American 19th century spiritual hymn, resolute and free' },
  'Harriet Tubman':            { gender: 'f', voiceId: VOICE_RACHEL, music: 'spiritual American folk, courageous and warm, 1850s north star' },
  'William James':             { gender: 'm', voiceId: VOICE_JOSH,   music: 'American Victorian piano, pragmatic and warm, 1890s Harvard study' },
  'Booker T. Washington':      { gender: 'm', voiceId: VOICE_JOSH,   music: 'American late 19th century hymn, dignified and determined' },
  'Charles Dickens':           { gender: 'm', voiceId: VOICE_JOSH,   music: 'Victorian English piano, warm and humane, 1850s London fireplace' },
  'John Muir':                 { gender: 'm', voiceId: VOICE_JOSH,   music: 'mountain wind and birdsong, open wilderness, Sierra Nevada morning' },
  'David Whyte':               { gender: 'm', voiceId: VOICE_JOSH,   music: 'Celtic acoustic guitar and wind, poetic and grounding, Irish coast' },
  "John O'Donohue":            { gender: 'm', voiceId: VOICE_JOSH,   music: 'Irish harp and coastal wind, Celtic blessing, ancient and warm' },
  'Wendell Berry':             { gender: 'm', voiceId: VOICE_JOSH,   music: 'American folk, earth and farm, quiet and deeply grounded' },
  'Oscar Wilde':               { gender: 'm', voiceId: VOICE_JOSH,   music: 'Victorian English piano, witty and elegant, 1890s salon' },
  'Friedrich Nietzsche':       { gender: 'm', voiceId: VOICE_JOSH,   music: 'German romantic piano, intense and searching, 1880s mountain' },
  'Søren Kierkegaard':         { gender: 'm', voiceId: VOICE_JOSH,   music: 'Danish chamber strings, existential and searching, 1840s Copenhagen' },
  'e.e. cummings':             { gender: 'm', voiceId: VOICE_JOSH,   music: 'jazz piano, playful and modern, 1920s American spring' },
  'Neil deGrasse Tyson':       { gender: 'm', voiceId: VOICE_JOSH,   music: 'cosmic ambient synth, wonder-filled and vast, spinning galaxies' },
  'J.R.R. Tolkien':            { gender: 'm', voiceId: VOICE_JOSH,   music: 'Celtic orchestral, mythic and warm, English shire and deep forest' },
  'Kabir':                     { gender: 'm', voiceId: VOICE_JOSH,   music: 'Indian folk devotional, ecstatic and simple, 15th century weaver song' },
  'Jorge Luis Borges':         { gender: 'm', voiceId: VOICE_JOSH,   music: 'Argentine tango undertone, labyrinthine and literary, Buenos Aires night' },
  'Neale Donald Walsch':       { gender: 'm', voiceId: VOICE_JOSH,   music: 'modern spiritual ambient, conversational and warm, gentle synth' },
  'Abraham Lincoln':           { gender: 'm', voiceId: VOICE_JOSH,   music: 'American 19th century hymn, dignified and earnest, candlelight' },
  'Aesop':                     { gender: 'm', voiceId: VOICE_JOSH,   music: 'ancient Greek lyre, simple and wise, fable morning' },
  'Marcus Tullius Cicero':     { gender: 'm', voiceId: VOICE_JOSH,   music: 'Roman chamber strings, eloquent and noble, Forum afternoon' },
  'John Ruskin':               { gender: 'm', voiceId: VOICE_JOSH,   music: 'Victorian English strings, thoughtful and earnest, 1840s countryside' },
  'Oliver Wendell Holmes Sr.': { gender: 'm', voiceId: VOICE_JOSH,   music: 'American Victorian piano, warm and wise, 1880s New England' },
  'Stephen Chbosky':           { gender: 'm', voiceId: VOICE_JOSH,   music: 'indie folk guitar, tender and contemporary, coming of age warmth' },
  'Jack Canfield':             { gender: 'm', voiceId: VOICE_JOSH,   music: 'uplifting contemporary piano, motivational and warm' },
  'Benjamin Spock':            { gender: 'm', voiceId: VOICE_JOSH,   music: 'warm 1950s American piano, reassuring and gentle' },
  'John Lubbock':              { gender: 'm', voiceId: VOICE_JOSH,   music: 'Victorian English pastoral piano, gentle and restful, 1890s' },
  'Zen proverb':               { gender: 'm', voiceId: VOICE_JOSH,   music: 'zen ambient, soft bells and open silence' },
  'Japanese proverb':          { gender: 'm', voiceId: VOICE_JOSH,   music: 'Japanese koto strings, gentle and wise, autumn morning' },
  'Native American proverb':   { gender: 'm', voiceId: VOICE_JOSH,   music: 'native American flute, earth and sky, sacred and still' },
  'Chinese proverb':           { gender: 'm', voiceId: VOICE_JOSH,   music: 'ancient Chinese guqin, timeless wisdom, morning mist' },
  'Persian adage':             { gender: 'm', voiceId: VOICE_JOSH,   music: 'Persian strings and wind, ancient and warm, desert dusk' },
  'Maya Angelou':              { gender: 'f', voiceId: VOICE_RACHEL, music: 'warm gospel piano, courageous and soulful, American South' },
  'Brené Brown':               { gender: 'f', voiceId: VOICE_RACHEL, music: 'warm acoustic guitar, intimate and open, contemporary courage' },
  'Mary Oliver':               { gender: 'f', voiceId: VOICE_RACHEL, music: 'birdsong and morning wind, attentive and still, New England field' },
  'Pema Chödrön':              { gender: 'f', voiceId: VOICE_RACHEL, music: 'tibetan bowls, compassionate and spacious, Buddhist sky' },
  'Tara Brach':                { gender: 'f', voiceId: VOICE_RACHEL, music: 'soft meditation ambient, compassionate and open, forest bells' },
  'Louise Hay':                { gender: 'f', voiceId: VOICE_RACHEL, music: 'uplifting soft piano, loving and affirming, contemporary healing' },
  'Toni Morrison':             { gender: 'f', voiceId: VOICE_RACHEL, music: 'warm jazz piano, powerful and soulful, American literature' },
  'Audre Lorde':               { gender: 'f', voiceId: VOICE_RACHEL, music: 'warm spoken word rhythm, powerful and poetic, 1970s' },
  'Eleanor Roosevelt':         { gender: 'f', voiceId: VOICE_RACHEL, music: 'American 1940s piano, dignified and courageous, New Deal warmth' },
  'Oprah Winfrey':             { gender: 'f', voiceId: VOICE_RACHEL, music: 'warm contemporary piano, uplifting and expansive, possibility' },
  'Elizabeth Gilbert':         { gender: 'f', voiceId: VOICE_RACHEL, music: 'warm acoustic guitar, journeying and open, contemporary wandering' },
  'Glennon Doyle':             { gender: 'f', voiceId: VOICE_RACHEL, music: 'contemporary folk piano, brave and intimate, untamed heart' },
  'Anaïs Nin':                 { gender: 'f', voiceId: VOICE_RACHEL, music: 'French cafe jazz, literary and sensual, 1940s Paris night' },
  'Simone de Beauvoir':        { gender: 'f', voiceId: VOICE_RACHEL, music: 'French existentialist cafe strings, intellectual and warm, 1940s' },
  'Octavia Butler':            { gender: 'f', voiceId: VOICE_RACHEL, music: 'afrofuturist ambient, powerful and visionary, parable rhythm' },
  'Florence Scovel Shinn':     { gender: 'f', voiceId: VOICE_RACHEL, music: 'warm 1920s piano, faithful and affirming, divine plan' },
};

const DEFAULT_META = { gender: 'm', voiceId: VOICE_JOSH, music: 'ambient meditation, warm and grounding, soft drone' };

export function getAuthorMeta(author) {
  return AUTHORS[author] || DEFAULT_META;
}
